kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: cirrusci/flutter:stable
    commands:
      - flutter pub get

  - name: format
    image: cirrusci/flutter:stable
    commands:
      - flutter format --set-exit-if-changed .

  - name: analyze
    image: cirrusci/flutter:stable
    commands:
      - flutter analyze

  - name: test
    image: cirrusci/flutter:stable
    commands:
      - flutter test

  - name: build-web
    image: cirrusci/flutter:stable
    commands:
      - flutter build web

  - name: build-apk
    image: cirrusci/flutter:stable
    commands:
      - flutter build apk

  - name: build-linux
    image: cirrusci/flutter:stable
    commands:
      - flutter build linux

  - name: build-windows
    image: cirrusci/flutter:stable
    commands:
      - flutter build windows

  - name: build-macos
    image: cirrusci/flutter:stable
    commands:
      - flutter build macos

  - name: build-tvos
    image: cirrusci/flutter:stable
    commands:
      - flutter build tvos

  - name: build-wearos
    image: cirrusci/flutter:stable
    commands:
      - flutter build wearos

  - name: build-freebsd
    image: cirrusci/flutter:stable
    commands:
      - flutter build freebsd

  - name: build-fuchsia
    image: cirrusci/flutter:stable
    commands:
      - flutter build fuchsia

  - name: build-harmonyos
    image: cirrusci/flutter:stable
    commands:
      - flutter build harmonyos

  - name: build-tizen
    image: cirrusci/flutter:stable
    commands:
      - flutter build tizen

  - name: build-embedded
    image: cirrusci/flutter:stable
    commands:
      - flutter build embedded
