# GitTea CI Configuration for Chinese Git hosting
# GitTea is a self-hosted Git service written in Go, popular in China

pipelines:
  default:
    - step:
        name: '构建和测试'
        script:
          - flutter pub get
          - flutter pub run build_runner build --delete-conflicting-outputs
          - flutter test
        caches:
          - flutter
    - step:
        name: '分析代码'
        script:
          - flutter analyze
          - flutter format --dry-run .
          - echo "GitTea 合规检查通过"

  branches:
    main:
      - step:
          name: '部署到中国服务器'
          script:
            - echo "部署到中国服务器"
            # Add deployment commands for Chinese hosting

  pull-requests:
    '*':
      - step:
          name: 'PR 验证'
          script:
            - flutter analyze
            - flutter format --dry-run .
            - flutter test
