version: '3.9'
services:
  synapse:
    image: matrixdotorg/synapse:latest
    restart: always
    volumes:
    - ./data/synapse:/data
    environment:
    - SYNAPSE_SERVER_NAME=node.marinchik.ink
    - SYNAPSE_REPORT_STATS=yes
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.synapse.rule=Host(`matrix.node.marinchik.ink`)
    - traefik.http.routers.synapse.entrypoints=websecure
    - traefik.http.routers.synapse.tls=true
  traefik:
    image: traefik:v2.11
    command:
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - --api.insecure=true
    - --providers.file.filename=/etc/traefik/traefik_dynamic.toml
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    - ./traefik/traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - matrix
  certbot:
    image: certbot/certbot
    volumes:
    - ./certbot:/etc/letsencrypt
    entrypoint: sleep
    command: infinity
    networks:
    - matrix
  bridge_telegram:
    image: mautrix/telegram
    restart: always
    volumes:
    - ./data/telegram:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_telegram.rule=Host(`telegram.node.marinchik.ink`)
    - traefik.http.routers.bridge_telegram.entrypoints=websecure
    - traefik.http.routers.bridge_telegram.tls=true
  bridge_signal:
    image: mautrix/signal
    restart: always
    volumes:
    - ./data/signal:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_signal.rule=Host(`signal.node.marinchik.ink`)
    - traefik.http.routers.bridge_signal.entrypoints=websecure
    - traefik.http.routers.bridge_signal.tls=true
  bridge_whatsapp:
    image: mautrix/whatsapp
    restart: always
    volumes:
    - ./data/whatsapp:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_whatsapp.rule=Host(`whatsapp.node.marinchik.ink`)
    - traefik.http.routers.bridge_whatsapp.entrypoints=websecure
    - traefik.http.routers.bridge_whatsapp.tls=true
  bridge_discord:
    image: mautrix/discord
    restart: always
    volumes:
    - ./data/discord:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_discord.rule=Host(`discord.node.marinchik.ink`)
    - traefik.http.routers.bridge_discord.entrypoints=websecure
    - traefik.http.routers.bridge_discord.tls=true
  bridge_facebook:
    image: mautrix/facebook
    restart: always
    volumes:
    - ./data/facebook:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_facebook.rule=Host(`facebook.node.marinchik.ink`)
    - traefik.http.routers.bridge_facebook.entrypoints=websecure
    - traefik.http.routers.bridge_facebook.tls=true
  bridge_instagram:
    image: mautrix/instagram
    restart: always
    volumes:
    - ./data/instagram:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_instagram.rule=Host(`instagram.node.marinchik.ink`)
    - traefik.http.routers.bridge_instagram.entrypoints=websecure
    - traefik.http.routers.bridge_instagram.tls=true
  bridge_googlechat:
    image: mautrix/googlechat
    restart: always
    volumes:
    - ./data/googlechat:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_googlechat.rule=Host(`googlechat.node.marinchik.ink`)
    - traefik.http.routers.bridge_googlechat.entrypoints=websecure
    - traefik.http.routers.bridge_googlechat.tls=true
  bridge_slack:
    image: mautrix/slack
    restart: always
    volumes:
    - ./data/slack:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_slack.rule=Host(`slack.node.marinchik.ink`)
    - traefik.http.routers.bridge_slack.entrypoints=websecure
    - traefik.http.routers.bridge_slack.tls=true
  bridge_twitter:
    image: mautrix/twitter
    restart: always
    volumes:
    - ./data/twitter:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_twitter.rule=Host(`twitter.node.marinchik.ink`)
    - traefik.http.routers.bridge_twitter.entrypoints=websecure
    - traefik.http.routers.bridge_twitter.tls=true
  bridge_bluesky:
    image: mautrix/bluesky
    restart: always
    volumes:
    - ./data/bluesky:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_bluesky.rule=Host(`bluesky.node.marinchik.ink`)
    - traefik.http.routers.bridge_bluesky.entrypoints=websecure
    - traefik.http.routers.bridge_bluesky.tls=true
  bridge_gmessages:
    image: mautrix/gmessages
    restart: always
    volumes:
    - ./data/gmessages:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_gmessages.rule=Host(`gmessages.node.marinchik.ink`)
    - traefik.http.routers.bridge_gmessages.entrypoints=websecure
    - traefik.http.routers.bridge_gmessages.tls=true
  bridge_email:
    image: mautrix/email
    restart: always
    volumes:
    - ./data/email:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_email.rule=Host(`email.node.marinchik.ink`)
    - traefik.http.routers.bridge_email.entrypoints=websecure
    - traefik.http.routers.bridge_email.tls=true
  bridge_hookshot:
    image: mautrix/hookshot
    restart: always
    volumes:
    - ./data/hookshot:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_hookshot.rule=Host(`hookshot.node.marinchik.ink`)
    - traefik.http.routers.bridge_hookshot.entrypoints=websecure
    - traefik.http.routers.bridge_hookshot.tls=true
  bridge_gvoice:
    image: mautrix/gvoice
    restart: always
    volumes:
    - ./data/gvoice:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_gvoice.rule=Host(`gvoice.node.marinchik.ink`)
    - traefik.http.routers.bridge_gvoice.entrypoints=websecure
    - traefik.http.routers.bridge_gvoice.tls=true
  bridge_gitter:
    image: mautrix/gitter
    restart: always
    volumes:
    - ./data/gitter:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_gitter.rule=Host(`gitter.node.marinchik.ink`)
    - traefik.http.routers.bridge_gitter.entrypoints=websecure
    - traefik.http.routers.bridge_gitter.tls=true
  bridge_xmpp:
    image: mautrix/xmpp
    restart: always
    volumes:
    - ./data/xmpp:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_xmpp.rule=Host(`xmpp.node.marinchik.ink`)
    - traefik.http.routers.bridge_xmpp.entrypoints=websecure
    - traefik.http.routers.bridge_xmpp.tls=true
  bridge_mattermost:
    image: mautrix/mattermost
    restart: always
    volumes:
    - ./data/mattermost:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_mattermost.rule=Host(`mattermost.node.marinchik.ink`)
    - traefik.http.routers.bridge_mattermost.entrypoints=websecure
    - traefik.http.routers.bridge_mattermost.tls=true
  bridge_mumble:
    image: mautrix/mumble
    restart: always
    volumes:
    - ./data/mumble:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_mumble.rule=Host(`mumble.node.marinchik.ink`)
    - traefik.http.routers.bridge_mumble.entrypoints=websecure
    - traefik.http.routers.bridge_mumble.tls=true
  bridge_wechat:
    image: mautrix/wechat
    restart: always
    volumes:
    - ./data/wechat:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_wechat.rule=Host(`wechat.node.marinchik.ink`)
    - traefik.http.routers.bridge_wechat.entrypoints=websecure
    - traefik.http.routers.bridge_wechat.tls=true
  bridge_kakaotalk:
    image: mautrix/kakaotalk
    restart: always
    volumes:
    - ./data/kakaotalk:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_kakaotalk.rule=Host(`kakaotalk.node.marinchik.ink`)
    - traefik.http.routers.bridge_kakaotalk.entrypoints=websecure
    - traefik.http.routers.bridge_kakaotalk.tls=true
  bridge_qq:
    image: mautrix/qq
    restart: always
    volumes:
    - ./data/qq:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_qq.rule=Host(`qq.node.marinchik.ink`)
    - traefik.http.routers.bridge_qq.entrypoints=websecure
    - traefik.http.routers.bridge_qq.tls=true
  bridge_heisenbridge:
    image: mautrix/heisenbridge
    restart: always
    volumes:
    - ./data/heisenbridge:/data
    networks:
    - matrix
    labels:
    - traefik.enable=true
    - traefik.http.routers.bridge_heisenbridge.rule=Host(`heisenbridge.node.marinchik.ink`)
    - traefik.http.routers.bridge_heisenbridge.entrypoints=websecure
    - traefik.http.routers.bridge_heisenbridge.tls=true
networks:
  matrix:
    driver: bridge
