
name: Docker Compose CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Docker Compose up
      run: docker-compose -f docker-compose.yml up -d
