display_name: Katya
package_name: katya
maintainer:
  name: Sorokin Dmitry Olegovich
  email: dmitry.justdev@gmail.com
priority: optional
section: x11
installed_size: 660400
essential: false
icon: assets/logo.png

postinstall_scripts:
  - echo "Installed my awesome Katya app!"
postuninstall_scripts:
  - echo "Surprised Pickachu face done!"

keywords:
  - Katya
  - REChain
  - Messaging
  - Utility

generic_name: Katya Client Application

categories:
  - Utility
  - Media

startup_notify: true

# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml
