name: katya
title: Katya ® 👽! 👩🏻‍💻 🕵🏻‍♀️
base: core22
version: git
license: GPL-3.0
summary: Hi! I'm Katya ® 👽! 👩🏻‍💻 🕵🏻‍♀️ An AI 🧠 multifunctional social blockchain platform! 👽*
description: Why 🚀 **Unleash the Future with Katya® - Your Ultimate AI Multifunctional Social Blockchain Platform!** 👽👩🏻‍💻🕵🏻‍♀️ Embark on a journey into the technological frontier as we proudly present the Katya® Super Platform—an unparalleled fusion of cutting-edge AI, multifunctionality, and the power of blockchain! 🌐💡 🌟 **Artificial Intelligence at its Zenith:** Katya's® state-of-the-art AI core redefines intelligent interactions. Seamlessly adapting to your preferences, this cognitive marvel transforms your digital experience into a personalized and efficient adventure. Get ready to witness a platform that learns, evolves, and connects with you on a whole new level. 🔗 **Multifunctional Mastery:** Elevate your digital presence with Katya's® multifunctional prowess. From social networking to content creation, financial transactions to smart contracts—Katya® is the epitome of versatility. It's not just a platform; it's a universe where all your needs find a home, effortlessly merging technology and human connection. 🌐 **Blockchain Brilliance:** Immerse yourself in the secure embrace of Katya's® blockchain technology. Your data is guarded, transactions are tamper-proof, and interactions are governed by the transparency and reliability of the blockchain. Trust and decentralization are not just promises; they are the pillars of Katya's® digital ecosystem. 🌍 **Connect Globally, Thrive Locally:** Break down geographical barriers and foster connections worldwide. Katya® redefines social networking by providing a global stage where cultures converge, collaborations flourish, and friendships know no boundaries. It's not just a platform; it's a bridge connecting minds across the globe. 🎨 **Aesthetic Simplicity, Functional Brilliance:** Immerse yourself in a sleek, modern, and user-friendly interface that defines Katya's® essence. Navigating through the platform is a visual delight, offering an intuitive experience that seamlessly integrates style and functionality. 🚀 **Fast-Track to Tomorrow:** Katya's® Super Platform propels you into the future of technology. Stay at the forefront with regular updates, ensuring you are always equipped with the latest features and security enhancements. Katya® isn't just a platform; it's a dynamic force constantly evolving to meet the demands of tomorrow. ⚡ **Katya® - Redefining Digital Horizons:** Join us as we reshape the landscape of digital interaction. Katya® is not just a platform; it's an extraordinary blend of AI, multifunctionality, and blockchain—an innovation that invites you to explore, connect, and thrive in a future where possibilities are limitless. 🌟👾🚀 **Katya ® 👽 aims to be built on the foundations of privacy, branding, and user experience!**  In an effort to pull others away from proprietary chat platforms to the Katya ® 👽 AI 🧠 REChain ®️ 🪐 Blockchain Node Network protocol. Katya ® 👽 AI 🧠 REChain ®️ 🪐 Blockchain Node Network with Matrix Protocol has the potential to be a standardized peer-to-peer chat protocol, [and in a way already is,](https://matrix.org/blog/2020/06/02/introducing-p-2-p-matrix) that allows people to communicate and control their conversation data. Email has been standardized in this way for a long time. For example, someone using Outlook can still email someone using Gmail. Most popular proprietary chat platforms do not adhere to a federated or decentralized protocol, and as a result have too much control over users data. If the goal for the Katya ® 👽 AI 🧠 REChain ®️ 🪐 Blockchain Node Network is adoption, a network effect is required for this paradigm shift. Katya ® 👽 makes the bet that the best way to attract new users is through strong branding and user experience. I hope that contributing and maintaining Katya ® 👽 will help kick start this process and help those in need.  Katya ® 👽 will always be a not for profit, community driven application.

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

parts:
  olm:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    source: https://gitlab.matrix.org/matrix-org/olm.git
    source-type: git
    source-tag: '3.2.14'
    build-packages:
      - g++

  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.7.12
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  katya:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      flutter pub get || true
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - libssl-dev
      - curl
      - jq
    stage-packages:
      - libsecret-1-0
      # - libjsoncpp25

slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: com.katya.wtf

apps:
  katya:
    command: bin/katya
    # extensions: [ gnome ]
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - network
      - network-manager
      - network-manager-observe
      - opengl
      - removable-media
      - browser-support
      - password-manager-service
    slots:
      - dbus-svc
    # Workaround for:
    # https://github.com/flutter-webrtc/flutter-webrtc/issues/1212#issuecomment-1611899344
    environment:
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
