name: Accessibility Testing

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  accessibility-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Run accessibility tests
      run: flutter test test/accessibility/

    - name: Check for accessibility issues
      run: |
        # Add custom accessibility checks here
        echo "Running accessibility analysis..."
        flutter analyze --fatal-infos

    - name: Upload accessibility report
      uses: actions/upload-artifact@v3
      with:
        name: accessibility-report
        path: accessibility-report.json
