name: Load Testing

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Test duration in seconds'
        required: false
        default: '60'
      vus:
        description: 'Virtual users'
        required: false
        default: '10'
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install k6
      run: |
        curl https://github.com/grafana/k6/releases/download/v0.45.0/k6-v0.45.0-linux-amd64.tar.gz -L | tar xvz
        sudo mv k6-v0.45.0-linux-amd64/k6 /usr/local/bin/

    - name: Create test script
      run: |
        cat > load-test.js << 'EOF'
        import http from 'k6/http';
        import { check, sleep } from 'k6';

        export let options = {
          stages: [
            { duration: '2m', target: 100 }, // Ramp up to 100 users over 2 minutes
            { duration: '5m', target: 100 }, // Stay at 100 users for 5 minutes
            { duration: '2m', target: 200 }, // Ramp up to 200 users over 2 minutes
            { duration: '5m', target: 200 }, // Stay at 200 users for 5 minutes
            { duration: '2m', target: 0 },   // Ramp down to 0 users over 2 minutes
          ],
          thresholds: {
            http_req_duration: ['p(99)<1500'], // 99% of requests must complete below 1.5s
            http_req_failed: ['rate<0.1'],     // Error rate must be below 10%
          },
        };

        const BASE_URL = 'https://katya.rechain.network'; // Replace with your actual URL

        export default function () {
          let responses = http.batch([
            ['GET', `${BASE_URL}/`],
            ['GET', `${BASE_URL}/status`],
          ]);

          check(responses[0], {
            'status is 200': (r) => r.status === 200,
            'response time < 500ms': (r) => r.timings.duration < 500,
          });

          sleep(1);
        }
        EOF

    - name: Run load test
      run: k6 run load-test.js

    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: load-test-results
        path: |
          *.html
          *.json
